### PR TITLE
Transform sequences act as the identity when empty.

### PR DESCRIPTION
**Pull request by bogovicj**
* override isIdentity method
* doc this behavior
* add test

see  #24

### CODE REVIEW

**Comment by imagejan** [comment]
What about the case of an `InvertibleRealTransform` directly followed by its `inverse()`? Should this case be covered as well?
If not, I'd suggest adding some comment to the javadoc of `RealTransformSequence#isIdentity()`, stating "if false, that doesn't guarantee that the sequence is _not_ an identity transform effectively" or some such.

**Comment by bogovicj** [comment]
@imagejan , 
Yea good point.  I'd go with adding that line to the javadoc, and not having the sequence cover that case.

**Comment by bogovicj** [comment]
Added a section in the documentation along the lines of what you wrote above, @imagejan , thanks!

**Comment by axtimwalde** [comment]
@bogovic can you move this doc comment into the javadoc of the `isIdentity` method?

**Comment by bogovicj** [comment]
@axtimwalde  ya, that makes more sense.  Done.

**Pull request merged**
