### PR TITLE
Position fields, mixed transform, and transition

### PR DESCRIPTION
**Pull request by axtimwalde**
This introduces real and discrete accesses over single axis positions, a real transform that mixes two
real transforms and an n-dimensional transition transform that transitions between two n-1 dimensional
transforms (which uses the mixing transform).  @tpietzsch @dietzc @StephanPreibisch objections?

### CODE REVIEW

**Comment by tpietzsch** [comment]
@axtimwalde Seems very useful!
I would rather put `PositionRandomAccessible`, `RealPositionRealRandomAccessible` into imglib2 core.

Are you sure you want to not support the `apply( float[] ... )` version in `InterpolatedRealTransform`?

**Comment by axtimwalde** [comment]
> I would rather put PositionRandomAccessible, RealPositionRealRandomAccessible into imglib2 core

I thought so too but then couldn't decide into which package to to put it `net.imglib2.position` ?

**Comment by axtimwalde** [comment]
> Are you sure you want to not support the apply( float[] ... ) version in InterpolatedRealTransform?

No, that is lazy error.  Thanks for spotting this.  I am actually angry that we have the float[] methods in the first place.  Never use them.

**Comment by tpietzsch** [comment]
> I thought so too but then couldn't decide into which package to to put it net.imglib2.position ?

sounds good!

**Comment by tpietzsch** [comment]
> No, that is lazy error. Thanks for spotting this. I am actually angry that we have the float[] methods in the first place. Never use them. What do you think about deprecating them? Like in many other cases, I have the choice now to carry around some superfluous float[] arrays or implement it inefficiently by copy+conversion. Doing the latter now.

I'm fine with deprecating them.

How about you put the inefficiently copy+conversion `float[]` method into the interface as a (deprecated) default method. Then we could get rid of all implementations right away...

**Comment by axtimwalde** [comment]
> How about you put the inefficiently copy+conversion float[] method into the interface as a (deprecated) default method. Then we could get rid of all implementations right away...

That would make most of the existing implementations even worse.  Let me think about it a little longer...

**Comment by axtimwalde** [comment]
@tpietzsch I did as you said https://github.com/imglib/imglib2-realtransform/pull/12 , but did not yet delete all existing implementations because we can do that easier when removing the method.

**Comment by tpietzsch** [comment]
what about putting `PositionRandomAccessible`, `RealPositionRealRandomAccessible` into imglib2 core? Package `net.imglib2.position` sounds fine to me

**Comment by axtimwalde** [comment]
@tpietzsch already done, following your earlier positive comment https://github.com/imglib/imglib2/commit/59cf72243782679af46aa29928879504ddb36f29

**Comment by tpietzsch** [comment]
oh sorry, I missed that!

**Pull request merged**
