### PR TITLE
feat: bounding box estimation for RealTransformed RealIntervals

### PR DESCRIPTION
**Pull request by bogovicj**
* add a test

### CODE REVIEW

**Comment by bogovicj** [comment]
This commit provides the functionality discussed in https://github.com/imglib/imglib2-realtransform/issues/6

Needs a new release of imglib2 including https://github.com/imglib/imglib2/commit/33c46610ec5311bb5836beb6c54075e198f34983

**Comment by bogovicj** [comment]
This is waiting on a new imglib2 core release as it depends on https://github.com/imglib/imglib2/commit/33c46610ec5311bb5836beb6c54075e198f34983

**Comment by tpietzsch** [comment]
@bogovicj I did not look in depth at the code, so forgive me if this is already taken care of...

It seems to me, that there can be unfavourable cases, when for example the sampled interval would be 19x19, and the spacing would be 10. Then the max point that would be checked is (10, 10), when we would prefer to also check the actual max corner at (19, 19). I think this is what happens with the current `LocalizingRealIntervalIterator`. Would it make sense to add an option to always include the max's, independent of sampling?

A variant of this is that something similar could happen due to rounding errors with real coordinates, even if the spacing is chosen well-intentioned.

**Comment by ctrueden** [comment]
@bogovicj I rebased this over the latest master branch. It does not compile right now though due to API skew.

**Pull request merged**
